import { LexaraLogo } from '../assets/LexaraLogo';

export default function TermsPage({ onHome }) {
  return (
    <div style={{ minHeight: '100vh', background: '#f8f6f1', padding: '24px 20px 60px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <div style={{ marginBottom: 24 }}>
          <LexaraLogo height={36} onClick={onHome} style={{ cursor: 'pointer' }} />
        </div>
        <article style={{ background: '#fff', border: '1px solid rgba(0,0,0,0.08)', borderRadius: 18, padding: 28, lineHeight: 1.75, color: '#2a2723' }}>
          <h1 style={{ margin: '0 0 6px', fontSize: 30 }}>Terms of Service</h1>
          <p style={{ margin: '0 0 22px', color: '#6b6560', fontSize: 13 }}>Last updated: May 26, 2026</p>
          <h2>1. Acceptance</h2>
          <p>By using Lexara, you agree to these terms. If you disagree, do not use the service.</p>
          <h2>2. What Lexara provides</h2>
          <p>Lexara is a document question-answering service. We do not guarantee the accuracy of AI-generated answers. Always verify important information from original source documents.</p>
          <h2>3. Acceptable use</h2>
          <p>You may not use Lexara to process: illegal content, content that violates others&apos; rights, or to attempt to circumvent our systems. Documents you upload must be ones you have the right to process.</p>
          <h2>4. Account responsibility</h2>
          <p>You are responsible for maintaining the security of your account. Notify us immediately of unauthorized access.</p>
          <h2>5. AI-generated content disclaimer</h2>
          <p>Answers generated by Lexara are produced by AI and may contain errors. Lexara is not liable for decisions made based on AI-generated content. For legal, medical, or financial decisions, consult qualified professionals.</p>
          <h2>6. Data and privacy</h2>
          <p>See our Privacy Policy for how we handle your data.</p>
          <h2>7. Service availability</h2>
          <p>We aim for high availability but do not guarantee uninterrupted access. We may modify or discontinue features with reasonable notice.</p>
          <h2>8. Termination</h2>
          <p>We reserve the right to suspend accounts that violate these terms. You may delete your account at any time.</p>
          <h2>9. Governing law</h2>
          <p>These terms are governed by applicable law. Disputes will be resolved through good-faith negotiation before any legal proceedings.</p>
          <h2>10. Contact</h2>
          <p>legal@lexara.ai</p>
        </article>
      </div>
    </div>
  );
}
